#!/usr/bin/env bash

function createIGRPrimary() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/igrprimary.example.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/igrprimary.example.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:7054 --caname ca-igrprimary --tls.certfiles "${PWD}/organizations/fabric-ca/igrprimary/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-igrprimary.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-igrprimary.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-igrprimary.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-igrprimary.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/igrprimary.example.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy igrprimary's CA cert to igrprimary's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/igrprimary.example.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/igrprimary/ca-cert.pem" "${PWD}/organizations/peerOrganizations/igrprimary.example.com/msp/tlscacerts/ca.crt"

  # Copy igrprimary's CA cert to igrprimary's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/igrprimary.example.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/igrprimary/ca-cert.pem" "${PWD}/organizations/peerOrganizations/igrprimary.example.com/tlsca/tlsca.igrprimary.example.com-cert.pem"

  # Copy igrprimary's CA cert to igrprimary's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/igrprimary.example.com/ca"
  cp "${PWD}/organizations/fabric-ca/igrprimary/ca-cert.pem" "${PWD}/organizations/peerOrganizations/igrprimary.example.com/ca/ca.igrprimary.example.com-cert.pem"

  infoln "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-igrprimary --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/igrprimary/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering user"
  set -x
  fabric-ca-client register --caname ca-igrprimary --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/igrprimary/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-igrprimary --id.name igrprimaryadmin --id.secret igrprimaryadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/igrprimary/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-igrprimary -M "${PWD}/organizations/peerOrganizations/igrprimary.example.com/peers/peer0.igrprimary.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/igrprimary/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/igrprimary.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/igrprimary.example.com/peers/peer0.igrprimary.example.com/msp/config.yaml"

  infoln "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-igrprimary -M "${PWD}/organizations/peerOrganizations/igrprimary.example.com/peers/peer0.igrprimary.example.com/tls" --enrollment.profile tls --csr.hosts peer0.igrprimary.example.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/igrprimary/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/igrprimary.example.com/peers/peer0.igrprimary.example.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/igrprimary.example.com/peers/peer0.igrprimary.example.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/igrprimary.example.com/peers/peer0.igrprimary.example.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/igrprimary.example.com/peers/peer0.igrprimary.example.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/igrprimary.example.com/peers/peer0.igrprimary.example.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/igrprimary.example.com/peers/peer0.igrprimary.example.com/tls/server.key"

  infoln "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:7054 --caname ca-igrprimary -M "${PWD}/organizations/peerOrganizations/igrprimary.example.com/users/User1@igrprimary.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/igrprimary/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/igrprimary.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/igrprimary.example.com/users/User1@igrprimary.example.com/msp/config.yaml"

  infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://igrprimaryadmin:igrprimaryadminpw@localhost:7054 --caname ca-igrprimary -M "${PWD}/organizations/peerOrganizations/igrprimary.example.com/users/Admin@igrprimary.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/igrprimary/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/igrprimary.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/igrprimary.example.com/users/Admin@igrprimary.example.com/msp/config.yaml"
}

function createIGRBank() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/igrbank.example.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/igrbank.example.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:8054 --caname ca-igrbank --tls.certfiles "${PWD}/organizations/fabric-ca/igrbank/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-igrbank.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-igrbank.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-igrbank.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-igrbank.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/igrbank.example.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy igrbank's CA cert to igrbank's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/igrbank.example.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/igrbank/ca-cert.pem" "${PWD}/organizations/peerOrganizations/igrbank.example.com/msp/tlscacerts/ca.crt"

  # Copy igrbank's CA cert to igrbank's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/igrbank.example.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/igrbank/ca-cert.pem" "${PWD}/organizations/peerOrganizations/igrbank.example.com/tlsca/tlsca.igrbank.example.com-cert.pem"

  # Copy igrbank's CA cert to igrbank's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/igrbank.example.com/ca"
  cp "${PWD}/organizations/fabric-ca/igrbank/ca-cert.pem" "${PWD}/organizations/peerOrganizations/igrbank.example.com/ca/ca.igrbank.example.com-cert.pem"

  infoln "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-igrbank --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/igrbank/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering user"
  set -x
  fabric-ca-client register --caname ca-igrbank --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/igrbank/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-igrbank --id.name igrbankadmin --id.secret igrbankadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/igrbank/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-igrbank -M "${PWD}/organizations/peerOrganizations/igrbank.example.com/peers/peer0.igrbank.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/igrbank/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/igrbank.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/igrbank.example.com/peers/peer0.igrbank.example.com/msp/config.yaml"

  infoln "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-igrbank -M "${PWD}/organizations/peerOrganizations/igrbank.example.com/peers/peer0.igrbank.example.com/tls" --enrollment.profile tls --csr.hosts peer0.igrbank.example.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/igrbank/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/igrbank.example.com/peers/peer0.igrbank.example.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/igrbank.example.com/peers/peer0.igrbank.example.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/igrbank.example.com/peers/peer0.igrbank.example.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/igrbank.example.com/peers/peer0.igrbank.example.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/igrbank.example.com/peers/peer0.igrbank.example.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/igrbank.example.com/peers/peer0.igrbank.example.com/tls/server.key"

  infoln "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:8054 --caname ca-igrbank -M "${PWD}/organizations/peerOrganizations/igrbank.example.com/users/User1@igrbank.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/igrbank/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/igrbank.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/igrbank.example.com/users/User1@igrbank.example.com/msp/config.yaml"

  infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://igrbankadmin:igrbankadminpw@localhost:8054 --caname ca-igrbank -M "${PWD}/organizations/peerOrganizations/igrbank.example.com/users/Admin@igrbank.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/igrbank/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/igrbank.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/igrbank.example.com/users/Admin@igrbank.example.com/msp/config.yaml"
}

function createOrderer() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/ordererOrganizations/example.com

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/ordererOrganizations/example.com

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:9054 --caname ca-orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/ordererOrganizations/example.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy orderer org's CA cert to orderer org's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/example.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/example.com/msp/tlscacerts/tlsca.example.com-cert.pem"

  # Copy orderer org's CA cert to orderer org's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/ordererOrganizations/example.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/example.com/tlsca/tlsca.example.com-cert.pem"

# Loop through each orderer (orderer, orderer2, orderer3, orderer4) to register and generate artifacts
  for ORDERER in orderer orderer2 orderer3 orderer4; do
    infoln "Registering ${ORDERER}"
    set -x
    fabric-ca-client register --caname ca-orderer --id.name ${ORDERER} --id.secret ${ORDERER}pw --id.type orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
    { set +x; } 2>/dev/null

    infoln "Generating the ${ORDERER} MSP"
    set -x
    fabric-ca-client enroll -u https://${ORDERER}:${ORDERER}pw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/example.com/orderers/${ORDERER}.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
    { set +x; } 2>/dev/null

    cp "${PWD}/organizations/ordererOrganizations/example.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/example.com/orderers/${ORDERER}.example.com/msp/config.yaml"

    # Workaround: Rename the signcert file to ensure consistency with Cryptogen generated artifacts
    if [ -f "${PWD}/organizations/ordererOrganizations/example.com/orderers/${ORDERER}.example.com/msp/signcerts/cert.pem" ]; then
      mv "${PWD}/organizations/ordererOrganizations/example.com/orderers/${ORDERER}.example.com/msp/signcerts/cert.pem" "${PWD}/organizations/ordererOrganizations/example.com/orderers/${ORDERER}.example.com/msp/signcerts/${ORDERER}.example.com-cert.pem"
    fi

    infoln "Generating the ${ORDERER} TLS certificates, use --csr.hosts to specify Subject Alternative Names"
    set -x
    fabric-ca-client enroll -u https://${ORDERER}:${ORDERER}pw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/example.com/orderers/${ORDERER}.example.com/tls" --enrollment.profile tls --csr.hosts ${ORDERER}.example.com --csr.hosts orderer.example.com --csr.hosts localhost --csr.hosts 10.48.59.78 --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
    { set +x; } 2>/dev/null

    # Copy the tls CA cert, server cert, server keystore to well known file names in the orderer's tls directory that are referenced by orderer startup config
    cp "${PWD}/organizations/ordererOrganizations/example.com/orderers/${ORDERER}.example.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/example.com/orderers/${ORDERER}.example.com/tls/ca.crt"
    cp "${PWD}/organizations/ordererOrganizations/example.com/orderers/${ORDERER}.example.com/tls/signcerts/"* "${PWD}/organizations/ordererOrganizations/example.com/orderers/${ORDERER}.example.com/tls/server.crt"
    cp "${PWD}/organizations/ordererOrganizations/example.com/orderers/${ORDERER}.example.com/tls/keystore/"* "${PWD}/organizations/ordererOrganizations/example.com/orderers/${ORDERER}.example.com/tls/server.key"

    # Copy orderer org's CA cert to orderer's /msp/tlscacerts directory (for use in the orderer MSP definition)
    mkdir -p "${PWD}/organizations/ordererOrganizations/example.com/orderers/${ORDERER}.example.com/msp/tlscacerts"
    cp "${PWD}/organizations/ordererOrganizations/example.com/orderers/${ORDERER}.example.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/example.com/orderers/${ORDERER}.example.com/msp/tlscacerts/tlsca.example.com-cert.pem"
  done

  # Register and generate artifacts for the orderer admin
  infoln "Registering the orderer admin"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name ordererAdmin --id.secret ordererAdminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the admin msp"
  set -x
  fabric-ca-client enroll -u https://ordererAdmin:ordererAdminpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/example.com/users/Admin@example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/example.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/example.com/users/Admin@example.com/msp/config.yaml"
}
